
spring:
  datasource:
    url: jdbc:postgresql://${STAGE_DB_HOST}:${STAGE_DB_PORT}/${STAGE_DB_NAME} 
    username: ${STAGE_DB_USERNAME}
    password: ${STAGE_DB_PASSWORD}

  # configurations specific to SMTP email
  mail:
    host: smtp.gmail.com
    port: 587
    username: info.numpyninja@gmail.com
    password: zzpkpsxuoagmurzy
    protocol: smtp
    #properties.mail.smtp:
    smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

app:
  frontend.url: ${FRONTEND_URL_HEROKU}
  #frontend.url: https://lms-frontend.herokuapp.com

security:
  app:
    jwtSecret: lmsAppSecretKeyTest
    jwtExpirationMs: 28800000  # 28800000 Ms = 8 hours
    jwtAcctActiveExpMs: 172800000 # 2 days in milli seconds



